name: 'Development Test'

on:
  workflow_run:
    workflows: ['Development Build']
    branches: [dev]
    types:
      - completed
      
jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        py-arch:
          - x64
        mpi:
          - openmpi
          - mpich
        os:
          - ubuntu-18.04
          
    steps:

    - name: Configure hostname
      run:  echo 127.0.0.1 `hostname` | sudo tee -a /etc/hosts > /dev/null

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Setup MPI (${{ matrix.mpi }})
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}
           
    - name: Install HDF5 and FFTW parallel libraries (open-mpi)
      if: matrix.mpi == 'openmpi'
      run: sudo apt install -y -q pkg-config libhdf5-openmpi-dev libfftw3-dev libfftw3-mpi-dev
      
    - name: Install HDF5 and FFTW parallel libraries (mpich)
      if: matrix.mpi == 'mpich'
      run: sudo apt install -y -q pkg-config libhdf5-openmpi-dev libfftw3-dev libfftw3-mpi-dev

    - name: Use Python ${{ matrix.py-version }} ${{ matrix.py-arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py-version }}
        architecture: ${{ matrix.py-arch }}
                               
    - name: Build and install mpi4py and h5py against local libraries
      run: |
        python -m pip -v install --no-cache-dir cython mpi4py
        python -m pip -v install --no-cache-dir --no-binary=h5py h5py

    - name: Download artifact from most recent build
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: dev_build.yaml
        branch: dev
        name: quop_mpi-py${{matrix.py-version}}-${{matrix.py-arch}}-${{matrix.mpi}}-${{matrix.os}}
        path: /home/runner/work/QuOp_MPI/QuOp_MPI
        
    - name: Install QuOp_MPI
      run: |
        cd /home/runner/work/QuOp_MPI/QuOp_MPI
        python -m pip install quop_mpi*whl

    - name: Run examples
      run: |
        cd /home/runner/work/QuOp_MPI/QuOp_MPI
        mpiexec -n 2 python examples/maxcut/maxcut.py
        python examples/maxcut/maxcut_plots.py
        mpiexec -n 2 python examples/maxcut/maxcut_parallel_qualities.py
        mpiexec -n 2 python examples/maxcut_extended/maxcut_extended.py
        python examples/maxcut_extended/maxcut_extended_plots.py
        mpiexec -n 2 python examples/maxcut_extended/maxcut_extended.py
        python examples/portfolio_rebalancing/qwoa_qualities.py
        mpiexec -n 2 python examples/portfolio_rebalancing/qwoa_portfolio.py
        mpiexec -n 2 python examples/portfolio_rebalancing/qaoaz_portfolio.py
        python examples/portfolio_rebalancing/portfolio_plots.py
        
    - name: Upload example plots artifacts
      uses: actions/upload-artifact@v2
      with:
        name: example_plots${{matrix.py-version}}-${{matrix.py-arch}}-${{matrix.mpi}}-${{matrix.os}}
        path: /home/runner/work/QuOp_MPI/QuOp_MPI/*.png
